// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type EntryDocumentDataSlicesSlice = never

/**
 * Content for Entry documents
 */
interface EntryDocumentData {
    /**
     * name field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField

    /**
     * image field in *Entry*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * imageAltText field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.imagealttext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    imagealttext: prismic.KeyTextField

    /**
     * type field in *Entry*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: MV
     * - **API ID Path**: entry.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    type: prismic.SelectField<
        | 'MV'
        | 'Editorial'
        | 'Film'
        | 'TV'
        | 'Awards'
        | 'Public'
        | 'Festival'
        | 'Concert'
        | 'Commerce'
        | 'Other',
        'filled'
    >

    /**
     * sourceHref field in *Entry*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.sourcehref
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    sourcehref: prismic.LinkField

    /**
     * source field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.source
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    source: prismic.KeyTextField

    /**
     * year field in *Entry*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    year: prismic.NumberField

    /**
     * location field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.location
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    location: prismic.KeyTextField

    /**
     * Slice Zone field in *Entry*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<EntryDocumentDataSlicesSlice> /**
     * Meta Description field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: entry.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Entry*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: entry.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Entry*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: entry.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Entry document from Prismic
 *
 * - **API ID**: `entry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EntryDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<Simplify<EntryDocumentData>, 'entry', Lang>

export type AllDocumentTypes = EntryDocument

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig,
        ): prismic.Client<AllDocumentTypes>
    }

    namespace Content {
        export type {
            EntryDocument,
            EntryDocumentData,
            EntryDocumentDataSlicesSlice,
            AllDocumentTypes,
        }
    }
}
